config/routes.rb
Rails.application.routes.draw do
  resources :evaluatees
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root to: 'visitors#index'
  devise_for :users  
  resources :users

  resources :evaluations

  resources :evaluators

  resources :subjects

  resources :evaluation_templates

  resources :ratings

  resources :comments

  resources :evaluation_templates_topics

  resources :rating_templates

  resources :topics

  post 'evaluators/select' => "evaluators#select"

  get 'send_email' => "evaluators#send_mail", as: 'send_mail'
  get "evaluations/:evaluation_id/preview" => "evaluations#preview", as: 'evaluation_preview'
end

app/models/rating_template.rb
# == Schema Information
#
# Table name: rating_templates
#
#  id               :integer          not null, primary key
#  low              :integer
#  high             :integer
#  low_description  :text
#  high_description :text
#  created_at       :datetime
#  updated_at       :datetime
#

class RatingTemplate < ActiveRecord::Base
  has_many :topics
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id                 :integer          not null, primary key
#  rating_template_id :integer
#  title              :string
#  description        :text
#  parent_id          :integer
#  lft                :integer
#  rgt                :integer
#  created_at         :datetime
#  updated_at         :datetime
#

class Topic < ActiveRecord::Base
  acts_as_nested_set
  
  has_and_belongs_to_many :evaluation_templates
  has_many :ratings
  has_many :comments
  belongs_to :rating_template
  
  def previous_ratings(evaluation_template_id, subject_id)
    prev_rating = []
    Evaluation.where(:evaluation_template_id => evaluation_template_id, :subject_id => subject_id).each do |eval|
      rating = Rating.where(:evaluation_id => eval.id, :topic_id => self.id).first 
      prev_rating << [rating.value, eval.evaluation_date] unless rating == nil
    end  
    prev_rating 
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_admin
  before_filter :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.xml
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = Topic.new(topic_params)
    @evaluation_template = EvaluationTemplate.find(params[:topic][:evaluation_template_id]) if params[:topic][:evaluation_template_id]

    respond_to do |format|
      if @topic.save
        if @evaluation_template
          @topic.evaluation_templates << @evaluation_template
        end

        if params[:topic][:parent_topic_id]
          parent_topic = Topic.find(params[:topic][:parent_topic_id])
          @topic.move_to_child_of(parent_topic)
        end

        format.html { redirect_to (@evaluation_template ? edit_evaluation_template_path(@evaluation_template) : topic_path(@topic)), :notice => 'Topic was successfully created.' }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update

    respond_to do |format|
      if @topic.update_attributes(topic_params)

        format.html { redirect_to(@topic, :notice => 'Topic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(topics_url) }
      format.xml  { head :ok }
    end
  end


  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:rating_template_id, :title, :description, :parent_id, :lft, :rgt)
  end
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-2">
      <br>
      <div class="actions">
        <%= f.submit "#{is_subtopic ? 'Create sub-topic' : 'Create topic' }" %>
      </div>
    </div>

    <%= f.hidden_field :evaluation_template_id, value: evaluation_template_id if evaluation_template_id %>

    <% if is_subtopic %>
        <%= f.hidden_field :parent_topic_id, value: parent_topic_id %>
    <% end %>


    <div class="col-md-4">
      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title, class: 'form-control', required: true %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description, class: 'form-control', required: true %>
      </div>
    </div>
  </div>

<% end %>

app/views/topics/_info.html.erb
<div class="row" style="margin-top: 30px;">
  <div class="col-md-12" style="height: 100px; border: 1px solid #d3d3d3; background-color: #ffffff; padding: 30px 15px; display: table">
    <h3>
      <%= topic.title %>
    </h3>

    <br>

    <%= topic.description %>
    <br>
    <br>
    <br>

    <% topic.children.each do |sub_topic| %>
        <div class="col-md-12" style="height: 100px; border: 1px solid #d3d3d3; background-color: #ffffff; padding: 30px 15px; display: table; margin-top: 10px">
          <h4><%= sub_topic.title %></h4>
          <%= sub_topic.description %>
        </div>
    <% end %>

    <% if params[:action] == 'edit' %>
        <div class="col-md-12" style="border: 1px solid #d3d3d3; padding-top: 10px; margin-top: 30px; background-color: #c8c8c8">
          <%= render partial: 'topics/form', locals: { evaluation_template_id: evaluation_template_id, is_subtopic: true, parent_topic_id: topic.id }%>
        </div>

        <br>
        <br><br>

  <% end %>

  </div>
</div>

app/views/topics/_topic_chart.html.erb
<div class="row" style="margin-top: 30px;">
  <div class="col-md-12" style="height: 100px; border: 1px solid #d3d3d3; background-color: #ffffff; padding: 30px 15px; display: table">
    <h3>
      <%= topic.title %>
    </h3>

    <br>

    <%= topic.description %>
    <br>
    <br>
    <br>

    <% if topic.children.count > 0 %>

        <% topic.children.each do |sub_topic| %>
            <div class="col-md-12" style="height: 300px; border: 1px solid #d3d3d3; background-color: #ffffff; padding: 30px 15px; display: table; margin-top: 10px">
              <div class="row" style="padding-left: 20px;">
                <h4><%= sub_topic.title %></h4>
                <%= sub_topic.description %>
              </div>

              <br><br>

              <div class="col-md-4">
                <div id="rating_chart_topic_<%= sub_topic.id %>" style="width: 100%; height: 250px;" class="rating_chart_topic"></div>
              </div>

              <div class="col-md-8">
                <div class="row">
                  <%= form_tag ratings_path, method: 'post', remote: true do %>
                      <%= hidden_field_tag 'rating[topic_id]', sub_topic.id %>
                      <%= hidden_field_tag 'rating[evaluation_id]', params[:id] %>
                      <%= hidden_field_tag 'rating[evaluator_id]', current_user.id %>
                      <%= hidden_field_tag 'rating[evaluatee_id]', params[:evaluatee_id] %>

                      <div class="col-md-6">
                        <%= select_tag 'rating[value]', options_for_select([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], nil), { include_blank: 'Rate', class: 'btn btn-default form-control', required: true } %>
                      </div>
                      <div class="col-md-6">
                        <%= submit_tag 'Rate', class: 'btn btn-default' %>
                      </div>
                  <% end %>
                </div>

                <br><br>

                <div class="row">
                  <%= form_tag comments_path, method: 'post', remote: true do %>
                      <%= hidden_field_tag 'comment[topic_id]', sub_topic.id %>
                      <%= hidden_field_tag 'comment[evaluation_id]', params[:id] %>
                      <%= hidden_field_tag 'comment[evaluator_id]', current_user.id %>
                      <%= hidden_field_tag 'comment[evaluatee_id]', params[:evaluatee_id] %>

                      <div class="col-md-12">
                        <%= label_tag 'Comment' %>
                        <br>
                        <%= text_area_tag 'comment[text]', nil, class: 'form-control', rows: 4 %>
                        <div class="row">
                          <div class="col-md-3">
                            <div style="margin-top: 20px;">
                              <%= submit_tag 'Comment', class: 'btn btn-default' %>
                            </div>
                          </div>

                          <div class="col-md-6"></div>

                          <div class="col-md-3" style="margin-top: 20px;">
                            <button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapse_comments_topic_<%= sub_topic.id %>" aria-expanded="false" aria-controls="collapseExample">
                              View comments history
                            </button>
                          </div>

                        </div>
                      </div>


                      <div class="collapse" id="collapse_comments_topic_<%= sub_topic.id %>">
                          <div class="col-md-12" id="list_comments_topic_<%= sub_topic.id %>" style="margin-top: 30px;">
                            <% sub_topic.comments.order('created_at desc').each do |cm| %>
                                <%= cm.text %>
                                <div class="row">
                                  <div class="col-md-9">
                                    <%= link_to("delete", comment_path(cm), :method => :delete, remote: true) %>
                                  </div>

                                  <div class="col-md-3">
                                    <small><%= time_ago_in_words(cm.created_at) %></small>
                                  </div>
                                </div><hr>
                            <% end %>
                          </div>
                      </div>

                  <% end %>
                </div>
              </div>

            </div>
        <% end %>
    <% else %>
        <div class="col-md-12" style="height: 300px; border: 1px solid #d3d3d3; background-color: #ffffff; padding: 30px 15px; display: table; margin-top: 10px">
          <div class="col-md-4">
            <div id="rating_chart_topic_<%= topic.id %>" style="width: 100%; height: 250px;" class="rating_chart_topic"></div>
          </div>

          <div class="col-md-8">
            <div class="row">
              <%= form_tag ratings_path, method: 'post', remote: true do %>
                  <%= hidden_field_tag 'rating[topic_id]', topic.id %>
                  <%= hidden_field_tag 'rating[evaluation_id]', params[:id] %>
                  <%= hidden_field_tag 'rating[evaluator_id]', current_user.id %>
                  <%= hidden_field_tag 'rating[evaluatee_id]', params[:evaluatee_id] %>

                  <div class="col-md-6">
                    <%= select_tag 'rating[value]', options_for_select([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], nil), { include_blank: 'Rate', class: 'btn btn-default form-control', required: true } %>
                  </div>
                  <div class="col-md-6">
                    <%= submit_tag 'Rate', class: 'btn btn-default' %>
                  </div>
              <% end %>
            </div>

            <br><br>

            <div class="row">
              <%= form_tag comments_path, method: 'post', remote: true do %>
                  <%= hidden_field_tag 'comment[topic_id]', topic.id %>
                  <%= hidden_field_tag 'comment[evaluation_id]', params[:id] %>
                  <%= hidden_field_tag 'comment[evaluator_id]', current_user.id %>
                  <%= hidden_field_tag 'comment[evaluatee_id]', params[:evaluatee_id] %>

                  <div class="col-md-12">
                    <%= label_tag 'Comment' %>
                    <br>
                    <%= text_area_tag 'comment[text]', nil, class: 'form-control', rows: 4 %>
                    <div class="row">
                      <div class="col-md-3">
                        <div style="margin-top: 20px;">
                          <%= submit_tag 'Comment', class: 'btn btn-default' %>
                        </div>
                      </div>

                      <div class="col-md-6"></div>

                      <div class="col-md-3" style="margin-top: 20px;">
                        <button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapse_comments_topic_<%= topic.id %>" aria-expanded="false" aria-controls="collapseExample">
                          View comments history
                        </button>
                      </div>

                    </div>
                  </div>


                  <div class="collapse" id="collapse_comments_topic_<%= topic.id %>">
                    <div class="">

                      <div class="col-md-12" id="list_comments_topic_<%= topic.id %>" style="margin-top: 30px;">
                        <% topic.comments.order('created_at desc').each do |cm| %>
                            <%= cm.text %>
                            <div class="row">
                              <div class="col-md-9">
                                <%= link_to("delete", comment_path(cm), :method => :delete, remote: true) %>
                              </div>

                              <div class="col-md-3">
                                <small><%= time_ago_in_words(cm.created_at) %></small>
                              </div>
                            </div><hr>
                        <% end %>
                      </div>

                    </div>
                  </div>

              <% end %>
            </div>
          </div>

        </div>
    <% end %>
    <br>
    <br><br>

  </div>
</div>

<script>
    $(function () {
        <% if topic.children.count > 0 %>
            <% topic.children.each do |sub_topic| %>
                <% last_ratings = sub_topic.ratings.where(evaluatee_id: params[:evaluatee_id]).last(5).reverse.to_a %>

                $("#rating_chart_topic_<%= sub_topic.id %>").highcharts({
                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: 'Rating history'
                    },
                    xAxis: {
                        type: 'category'
                    },
                    yAxis: {
                        title: {
                            text: 'Rating scale'
                        }

                    },
                    legend: {
                        enabled: false
                    },
                    plotOptions: {
                        series: {
                            borderWidth: 0,
                            dataLabels: {
        //                        enabled: true,
        //                        format: '{point.y:.1f}%'
                            }
                        }
                    },

                    tooltip: {
                        headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                        pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
                    },

                    series: [{
                        name: "Brands",
                        colorByPoint: true,
                        data: [{
                            name: "<%= last_ratings[4] ? last_ratings[4].created_at.strftime("%-m/%-d") : '' %>",
                            y: <%= last_ratings[4] ? last_ratings[4].value.to_i : 0 %>
                        }, {
                            name: "<%= last_ratings[3] ? last_ratings[3].created_at.strftime("%-m/%-d") : '' %>",
                            y: <%= last_ratings[3] ? last_ratings[3].value.to_i : 0 %>
                        }, {
                            name: "<%= last_ratings[2] ? last_ratings[2].created_at.strftime("%-m/%-d") : '' %>",
                            y: <%= last_ratings[2] ? last_ratings[2].value.to_i : 0 %>
                        }, {
                            name: "<%= last_ratings[1] ? last_ratings[1].created_at.strftime("%-m/%-d") : '' %>",
                            y: <%= last_ratings[1] ? last_ratings[1].value.to_i : 0 %>
                        }, {
                            name: "<%= last_ratings[0] ? last_ratings[0].created_at.strftime("%-m/%-d") : '' %>",
                            y: <%= last_ratings[0] ? last_ratings[0].value.to_i : 0 %>
                        }]
                    }]
                });
            <% end %>
        <% else %>
            <% last_ratings = topic.ratings.where(evaluatee_id: params[:evaluatee_id]).last(5).reverse.to_a %>

            $("#rating_chart_topic_<%= topic.id %>").highcharts({
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'Rating history'
                },
                xAxis: {
                    type: 'category'
                },
                yAxis: {
                    title: {
                        text: 'Rating scale'
                    }

                },
                legend: {
                    enabled: false
                },
                plotOptions: {
                    series: {
                        borderWidth: 0,
                        dataLabels: {
                            //                        enabled: true,
                            //                        format: '{point.y:.1f}%'
                        }
                    }
                },

                tooltip: {
                    headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                    pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
                },

                series: [{
                    name: "Brands",
                    colorByPoint: true,
                    data: [{
                        name: "<%= last_ratings[4] ? last_ratings[4].created_at.strftime("%-m/%-d") : '' %>",
                        y: <%= last_ratings[4] ? last_ratings[4].value.to_i : 0 %>
                    }, {
                        name: "<%= last_ratings[3] ? last_ratings[3].created_at.strftime("%-m/%-d") : '' %>",
                        y: <%= last_ratings[3] ? last_ratings[3].value.to_i : 0 %>
                    }, {
                        name: "<%= last_ratings[2] ? last_ratings[2].created_at.strftime("%-m/%-d") : '' %>",
                        y: <%= last_ratings[2] ? last_ratings[2].value.to_i : 0 %>
                    }, {
                        name: "<%= last_ratings[1] ? last_ratings[1].created_at.strftime("%-m/%-d") : '' %>",
                        y: <%= last_ratings[1] ? last_ratings[1].value.to_i : 0 %>
                    }, {
                        name: "<%= last_ratings[0] ? last_ratings[0].created_at.strftime("%-m/%-d") : '' %>",
                        y: <%= last_ratings[0] ? last_ratings[0].value.to_i : 0 %>
                    }]
                }]
            });
        <% end %>
    });

</script>

app/views/topics/_topic_preview.html.erb
<div class="row" style="margin-top: 30px;">
  <div class="col-md-12" style="height: 100px; border: 1px solid #d3d3d3; background-color: #ffffff; padding: 30px 15px; display: table">
    <h3>
      <%= topic.title %>
    </h3>

    <br>

    <%= topic.description %>
    <br>
    <br>
    <br>

    <% if topic.children.count > 0 %>

        <% topic.children.each do |sub_topic| %>
            <div class="col-md-12" style="height: 300px; border: 1px solid #d3d3d3; background-color: #ffffff; padding: 30px 15px; display: table; margin-top: 10px">
              <div class="row" style="padding-left: 20px;">
                <h4><%= sub_topic.title %></h4>
                <%= sub_topic.description %>
              </div>

              <br><br>

              <div class="col-md-4">
                <div id="rating_chart_topic_<%= sub_topic.id %>" style="width: 100%; height: 250px;" class="rating_chart_topic"></div>
              </div>

              <div class="col-md-8">


                <div class="row">
                  <div class="col-md-12" id="list_comments_topic_<%= sub_topic.id %>" style="margin-top: 30px;">
                    <% sub_topic.comments.order('created_at desc').each do |cm| %>
                        <%= cm.text %> <div style="text-align:right;"><small><%= time_ago_in_words(cm.created_at) %></small></div><hr>
                    <% end %>
                  </div>
                </div>
              </div>

            </div>
        <% end %>
    <% else %>
        <div class="col-md-12" style="height: 300px; border: 1px solid #d3d3d3; background-color: #ffffff; padding: 30px 15px; display: table; margin-top: 10px">
          <div class="col-md-4">
            <div id="rating_chart_topic_<%= topic.id %>" style="width: 100%; height: 250px;" class="rating_chart_topic"></div>
          </div>

          <div class="col-md-8">

            <div class="row">
              <div class="col-md-12" id="list_comments_topic_<%= topic.id %>" style="margin-top: 30px;">
                <% topic.comments.order('created_at desc').each do |cm| %>
                    <%= cm.text %> <div style="text-align:right;"><small><%= time_ago_in_words(cm.created_at) %></small></div><hr>
                <% end %>
              </div>
            </div>
          </div>

        </div>
    <% end %>
    <br>
    <br><br>

  </div>
</div>

<script>
    $(function () {
        <% if topic.children.count > 0 %>
        <% topic.children.each do |sub_topic| %>
        <% last_ratings = sub_topic.ratings.where(evaluatee_id: evaluatee_id).last(5).reverse.to_a %>

        $("#rating_chart_topic_<%= sub_topic.id %>").highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Rating history'
            },
            xAxis: {
                type: 'category'
            },
            yAxis: {
                title: {
                    text: 'Rating scale'
                }

            },
            legend: {
                enabled: false
            },
            plotOptions: {
                series: {
                    borderWidth: 0,
                    dataLabels: {
                        //                        enabled: true,
                        //                        format: '{point.y:.1f}%'
                    }
                }
            },

            tooltip: {
                headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
            },

            series: [{
                name: "Brands",
                colorByPoint: true,
                data: [{
                    name: "<%= last_ratings[4] ? last_ratings[4].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[4] ? last_ratings[4].value.to_i : 0 %>
                }, {
                    name: "<%= last_ratings[3] ? last_ratings[3].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[3] ? last_ratings[3].value.to_i : 0 %>
                }, {
                    name: "<%= last_ratings[2] ? last_ratings[2].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[2] ? last_ratings[2].value.to_i : 0 %>
                }, {
                    name: "<%= last_ratings[1] ? last_ratings[1].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[1] ? last_ratings[1].value.to_i : 0 %>
                }, {
                    name: "<%= last_ratings[0] ? last_ratings[0].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[0] ? last_ratings[0].value.to_i : 0 %>
                }]
            }]
        });
        <% end %>
        <% else %>
        <% last_ratings = topic.ratings.where(evaluatee_id: params[:evaluatee_id]).last(5).reverse.to_a %>

        $("#rating_chart_topic_<%= topic.id %>").highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Rating history'
            },
            xAxis: {
                type: 'category'
            },
            yAxis: {
                title: {
                    text: 'Rating scale'
                }

            },
            legend: {
                enabled: false
            },
            plotOptions: {
                series: {
                    borderWidth: 0,
                    dataLabels: {
                        //                        enabled: true,
                        //                        format: '{point.y:.1f}%'
                    }
                }
            },

            tooltip: {
                headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
            },

            series: [{
                name: "Brands",
                colorByPoint: true,
                data: [{
                    name: "<%= last_ratings[4] ? last_ratings[4].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[4] ? last_ratings[4].value.to_i : 0 %>
                }, {
                    name: "<%= last_ratings[3] ? last_ratings[3].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[3] ? last_ratings[3].value.to_i : 0 %>
                }, {
                    name: "<%= last_ratings[2] ? last_ratings[2].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[2] ? last_ratings[2].value.to_i : 0 %>
                }, {
                    name: "<%= last_ratings[1] ? last_ratings[1].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[1] ? last_ratings[1].value.to_i : 0 %>
                }, {
                    name: "<%= last_ratings[0] ? last_ratings[0].created_at.strftime("%-m/%-d") : '' %>",
                    y: <%= last_ratings[0] ? last_ratings[0].value.to_i : 0 %>
                }]
            }]
        });
        <% end %>
    });

</script>

app/views/topics/create.js.erb
$("#topics-list").append(
                "<h3>" +
                    "Topic <%= @topic.id %> <%= @topic.title %>" +
                "</h3>" +

                "<br>" +

                "<div class='row'>" +
                    '<div class="col-md-12" style="height: 100px; border: 1px solid #d3d3d3; background-color: #ffffff">' +
                        "<%= @topic.description %>" +
                    "</div>" +
                "</div>"
);

$("#new_evaluation_template").append(
        '<input class="form-control" type="hidden" name="topic_ids[]" value="<%= @topic.id %>">'
)

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Rating template</th>
    <th>Title</th>
    <th>Description</th>
    <th>Parent</th>
    <th>Lft</th>
    <th>Rgt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.rating_template_id %></td>
    <td><%= topic.title %></td>
    <td><%= topic.description %></td>
    <td><%= topic.parent_id %></td>
    <td><%= topic.lft %></td>
    <td><%= topic.rgt %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rating template:</b>
  <%= @topic.rating_template_id %>
</p>

<p>
  <b>Title:</b>
  <%= @topic.title %>
</p>

<p>
  <b>Description:</b>
  <%= @topic.description %>
</p>

<p>
  <b>Parent:</b>
  <%= @topic.parent_id %>
</p>

<p>
  <b>Lft:</b>
  <%= @topic.lft %>
</p>

<p>
  <b>Rgt:</b>
  <%= @topic.rgt %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>