config/routes.rb
Rails.application.routes.draw do
  resources :evaluatees
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root to: 'visitors#index'
  devise_for :users  
  resources :users

  resources :evaluations

  resources :evaluators

  resources :subjects

  resources :evaluation_templates

  resources :ratings

  resources :comments

  resources :evaluation_templates_topics

  resources :rating_templates

  resources :topics

  post 'evaluators/select' => "evaluators#select"

  get 'send_email' => "evaluators#send_mail", as: 'send_mail'
  get "evaluations/:evaluation_id/preview" => "evaluations#preview", as: 'evaluation_preview'
end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id            :integer          not null, primary key
#  evaluation_id :integer
#  topic_id      :integer
#  value         :decimal(, )
#  created_at    :datetime
#  updated_at    :datetime
#  evaluatee_id  :integer
#  evaluator_id  :integer
#

class Rating < ActiveRecord::Base
  belongs_to :evaluation
  belongs_to :topic
  belongs_to :evaluator
  belongs_to :evaluatee
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :authenticate_evaluator
  before_filter :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.xml
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.xml
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST evaluations/ratings
  # POST evaluations/ratings.xml
  # id            :integer          not null, primary key
  #  evaluation_id :integer
  #  topic_id      :integer
  #  value         :decimal(, )
  def create
    if Rating.where(
        evaluation_id: rating_params[:evaluation_id],
        topic_id: rating_params[:topic_id],
        evaluator_id: rating_params[:evaluator_id],
        evaluatee_id: rating_params[:evaluatee_id]
    ).exists?
      @rating = Rating.where(
          evaluation_id: rating_params[:evaluation_id],
          topic_id: rating_params[:topic_id],
          evaluator_id: rating_params[:evaluator_id],
          evaluatee_id: rating_params[:evaluatee_id]
      ).last

      @rating.update_attributes(value: rating_params[:value])
    else
      @rating = Rating.new(rating_params)
    end

    respond_to do |format|
      if @rating.save
        format.html { redirect_to(@rating, :notice => 'Rating was successfully created.') }
        format.xml  { render :xml => @rating, :status => :created, :location => @rating }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.xml
  def update
    respond_to do |format|
      if @rating.update_attributes(rating_params)
        format.html { redirect_to(@rating, :notice => 'Rating was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.xml
  def destroy
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to(ratings_url) }
      format.xml  { head :ok }
    end
  end

  private
  def set_rating
    @rating = Rating.find(params[:id])
  end

  def rating_params
    params.require(:rating).permit(:evaluation_id, :topic_id, :value, :evaluator_id, :evaluatee_id)
  end
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :evaluation_id %><br />
    <%= f.text_field :evaluation_id %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br />
    <%= f.text_field :topic_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/create.js.erb
$("select[name='rating[value]']").val(null);
//swal("Rate successfully",'','success');
location.reload();

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>Evaluation</th>
    <th>Topic</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.evaluation_id %></td>
    <td><%= rating.topic_id %></td>
    <td><%= rating.value %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Evaluation:</b>
  <%= @rating.evaluation_id %>
</p>

<p>
  <b>Topic:</b>
  <%= @rating.topic_id %>
</p>

<p>
  <b>Value:</b>
  <%= @rating.value %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>