config/routes.rb
Rails.application.routes.draw do
  resources :evaluatees
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root to: 'visitors#index'
  devise_for :users  
  resources :users

  resources :evaluations

  resources :evaluators

  resources :subjects

  resources :evaluation_templates

  resources :ratings

  resources :comments

  resources :evaluation_templates_topics

  resources :rating_templates

  resources :topics

  post 'evaluators/select' => "evaluators#select"

  get 'send_email' => "evaluators#send_mail", as: 'send_mail'
  get "evaluations/:evaluation_id/preview" => "evaluations#preview", as: 'evaluation_preview'
end

app/models/evaluation_templates_topic.rb
# == Schema Information
#
# Table name: evaluation_templates_topics
#
#  evaluation_template_id :integer          not null
#  topic_id               :integer          not null
#  created_at             :datetime
#  updated_at             :datetime
#

class EvaluationTemplatesTopic < ActiveRecord::Base
end

app/controllers/evaluation_templates_topics_controller.rb
class EvaluationTemplatesTopicsController < ApplicationController
  before_filter :authenticate_admin
  before_filter :set_evaluation_template_topic, only: [:show, :edit, :update, :destroy]

  # GET /evaluation_templates_topics
  # GET /evaluation_templates_topics.xml
  def index
    @evaluation_templates_topics = EvaluationTemplatesTopic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @evaluation_templates_topics }
    end
  end

  # GET /evaluation_templates_topics/1
  # GET /evaluation_templates_topics/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @evaluation_templates_topic }
    end
  end

  # GET /evaluation_templates_topics/new
  # GET /evaluation_templates_topics/new.xml
  def new
    @evaluation_templates_topic = EvaluationTemplatesTopic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @evaluation_templates_topic }
    end
  end

  # GET /evaluation_templates_topics/1/edit
  def edit
  end

  # POST /evaluation_templates_topics
  # POST /evaluation_templates_topics.xml
  def create
    @evaluation_templates_topic = EvaluationTemplatesTopic.new(evaluation_template_topic_params)

    respond_to do |format|
      if @evaluation_templates_topic.save
        format.html { redirect_to(@evaluation_templates_topic, :notice => 'Evaluation templates topic was successfully created.') }
        format.xml  { render :xml => @evaluation_templates_topic, :status => :created, :location => @evaluation_templates_topic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @evaluation_templates_topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /evaluation_templates_topics/1
  # PUT /evaluation_templates_topics/1.xml
  def update
    respond_to do |format|
      if @evaluation_templates_topic.update_attributes(evaluation_template_topic_params)
        format.html { redirect_to(@evaluation_templates_topic, :notice => 'Evaluation templates topic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @evaluation_templates_topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluation_templates_topics/1
  # DELETE /evaluation_templates_topics/1.xml
  def destroy
    @evaluation_templates_topic.destroy

    respond_to do |format|
      format.html { redirect_to(evaluation_templates_topics_url) }
      format.xml  { head :ok }
    end
  end


  private
  def set_evaluation_template_topic
    @evaluation_templates_topic = Comment.find(params[:id])
  end

#  evaluation_template_id :integer          not null
#  topic_id               :integer
  def evaluation_template_topic_params
    params.require(:evaluation_template_topic).permit(:topic_id, :evaluation_template_id)
  end
end

app/views/evaluation_templates_topics/_form.html.erb
<%= form_for(@evaluation_templates_topic) do |f| %>
  <% if @evaluation_templates_topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluation_templates_topic.errors.count, "error") %> prohibited this evaluation_templates_topic from being saved:</h2>

      <ul>
      <% @evaluation_templates_topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :evaluation_template_id %><br />
    <%= f.text_field :evaluation_template_id %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br />
    <%= f.text_field :topic_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evaluation_templates_topics/edit.html.erb
<h1>Editing evaluation_templates_topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluation_templates_topic %> |
<%= link_to 'Back', evaluation_templates_topics_path %>

app/views/evaluation_templates_topics/index.html.erb
<h1>Listing evaluation_templates_topics</h1>

<table>
  <tr>
    <th>Evaluation template</th>
    <th>Topic</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @evaluation_templates_topics.each do |evaluation_templates_topic| %>
  <tr>
    <td><%= evaluation_templates_topic.evaluation_template_id %></td>
    <td><%= evaluation_templates_topic.topic_id %></td>
    <td><%= link_to 'Show', evaluation_templates_topic %></td>
    <td><%= link_to 'Edit', edit_evaluation_templates_topic_path(evaluation_templates_topic) %></td>
    <td><%= link_to 'Destroy', evaluation_templates_topic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evaluation templates topic', new_evaluation_templates_topic_path %>

app/views/evaluation_templates_topics/new.html.erb
<h1>New evaluation_templates_topic</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluation_templates_topics_path %>

app/views/evaluation_templates_topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Evaluation template:</b>
  <%= @evaluation_templates_topic.evaluation_template_id %>
</p>

<p>
  <b>Topic:</b>
  <%= @evaluation_templates_topic.topic_id %>
</p>


<%= link_to 'Edit', edit_evaluation_templates_topic_path(@evaluation_templates_topic) %> |
<%= link_to 'Back', evaluation_templates_topics_path %>