config/routes.rb
Rails.application.routes.draw do
  resources :evaluatees
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root to: 'visitors#index'
  devise_for :users  
  resources :users

  resources :evaluations

  resources :evaluators

  resources :subjects

  resources :evaluation_templates

  resources :ratings

  resources :comments

  resources :evaluation_templates_topics

  resources :rating_templates

  resources :topics

  post 'evaluators/select' => "evaluators#select"

  get 'send_email' => "evaluators#send_mail", as: 'send_mail'
  get "evaluations/:evaluation_id/preview" => "evaluations#preview", as: 'evaluation_preview'
end

app/models/evaluatee.rb
# == Schema Information
#
# Table name: evaluatees
#
#  id           :integer          not null, primary key
#  name         :string
#  email        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  description  :string
#  evaluator_id :integer
#

class Evaluatee < ActiveRecord::Base
  has_many :evaluations
  belongs_to :evaluator, :class_name => 'User', :foreign_key => 'evaluator_id'
end

app/controllers/evaluatees_controller.rb
class EvaluateesController < ApplicationController
  before_filter :authenticate_evaluator
  before_action :set_evaluatee, only: [:show, :edit, :update, :destroy]

  # GET /evaluatees
  # GET /evaluatees.json
  def index
    @evaluatees = current_user.evaluatees
  end

  # GET /evaluatees/1
  # GET /evaluatees/1.json
  def show
  end

  # GET /evaluatees/new
  def new
    @evaluatee = Evaluatee.new
  end

  # GET /evaluatees/1/edit
  def edit
  end

  # POST /evaluatees
  # POST /evaluatees.json
  def create
    @evaluatee = Evaluatee.new(evaluatee_params)
    @evaluatee.evaluator  = current_user

    respond_to do |format|
      if @evaluatee.save
        format.html { redirect_to @evaluatee, notice: 'Evaluatee was successfully created.' }
        format.json { render :show, status: :created, location: @evaluatee }
      else
        format.html { render :new }
        format.json { render json: @evaluatee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluatees/1
  # PATCH/PUT /evaluatees/1.json
  def update
    respond_to do |format|
      if @evaluatee.update(evaluatee_params)
        format.html { redirect_to @evaluatee, notice: 'Evaluatee was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluatee }
      else
        format.html { render :edit }
        format.json { render json: @evaluatee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluatees/1
  # DELETE /evaluatees/1.json
  def destroy
    @evaluatee.destroy
    respond_to do |format|
      format.html { redirect_to evaluatees_url, notice: 'Evaluatee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluatee
      @evaluatee = Evaluatee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluatee_params
      params.require(:evaluatee).permit(:name, :email)
    end
end

app/helpers/evaluatees_helper.rb
module EvaluateesHelper
end

app/views/evaluatees/_form.html.slim
= form_for @evaluatee do |f|
  - if @evaluatee.errors.any?
    #error_explanation
      h2 = "#{pluralize(@evaluatee.errors.count, "error")} prohibited this evaluatee from being saved:"
      ul
        - @evaluatee.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    br
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :email
    br
    = f.text_field :email, class: 'form-control'
  .actions = f.submit

app/views/evaluatees/edit.html.slim
h1 Editing evaluatee

== render 'form'

= link_to 'Show', @evaluatee
'|
= link_to 'Back', evaluatees_path

app/views/evaluatees/index.html.slim
br
br
= link_to 'New Evaluatee', new_evaluatee_path, class: 'btn btn-default'
br

h2 Listing evaluatees

br

table.table.table-striped
  thead
    tr
      th Name
      th Email
      th colspan="3" Actions
  tbody
    - @evaluatees.each do |evaluatee|
      tr
        td = evaluatee.name
        td = evaluatee.email
        td = link_to 'Show', evaluatee
        td = link_to 'Edit', edit_evaluatee_path(evaluatee)
        td = link_to 'Destroy', evaluatee, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/evaluatees/new.html.slim
h1 New evaluatee

== render 'form'

= link_to 'Back', evaluatees_path

app/views/evaluatees/show.html.slim
p#notice = notice

p
  strong Name:
  = @evaluatee.name
p
  strong Email:
  = @evaluatee.email

= link_to 'Edit', edit_evaluatee_path(@evaluatee)
'|
= link_to 'Back', evaluatees_path